<!DOCTYPE html>
<html>
<head>
    <title>Payment Tracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="css/bootstrap.css" rel="stylesheet" media="screen">
</head>
<body>

<!--Inject Container-->

$partials/header()$
<section>$(body_template)()$</section>
$partials/footer()$

<script src="http://code.jquery.com/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>