<!DOCTYPE html>
<html>
<head>
    <title>Payment Tracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="css/bootstrap.css" rel="stylesheet" media="screen">
</head>
<body>

<!--Inject Container-->

$partials/header()$
<section>$(body_template)()$</section>
$partials/footer()$

<script src="http://code.jquery.com/jquery.js"></script>
<script src="http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
<script src="http://ajax.cdnjs.com/ajax/libs/underscore.js/1.1.6/underscore-min.js"></script>
<script src="http://ajax.cdnjs.com/ajax/libs/backbone.js/0.3.3/backbone-min.js"></script>
<script src="/js/bootstrap.min.js"></script>
</body>
</html>